apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sovannlyna-ui-mastervv-certificate
  namespace: sovannlyna-ui-mastervv
spec:
  secretName: sovannlyna-ui-mastervv-secret-tls
  commonName: sovannlyna-ui-mastervv.assessify.org
  dnsNames:
  - sovannlyna-ui-mastervv.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
